from __future__ import annotations

import re
from typing import Any, TYPE_CHECKING

from app.exceptions.app_errors import AntiHallucinationError

if TYPE_CHECKING:
    from app.resources.resource_manager import ResourceManager

_PLACEHOLDER_PATTERNS = [
    re.compile(r"\b(unknown|n/a|na|null|none|tbd|todo|test|sample|example|placeholder)\b", re.I),
    re.compile(r"\b(123 main|main street|fake street|any street|your address|shipping address)\b", re.I),
    re.compile(r"\b(john doe|jane doe|acme|foo|bar)\b", re.I),
    re.compile(r"^(.)\1{4,}$", re.I),
    re.compile(r"^(0{6,}|1{6,}|9{6,}|123456\d*|987654\d*)$"),
    re.compile(r"\b(lorem ipsum|asdf|qwerty|abcdef)\b", re.I),
]


def _make_issue(
    path: str,
    code: str,
    message: str,
    confidence: float = 0.2,
    suggestions: list | None = None,
) -> dict[str, Any]:
    return {"path": path, "code": code, "message": message, "confidence": confidence, "suggestions": suggestions or []}


def _inspect_string(path: str, value: str, issues: list) -> None:
    if not value.strip():
        issues.append(_make_issue(path, "EMPTY_STRING", "Empty string", 0.0))
        return
    if any(p.search(value) for p in _PLACEHOLDER_PATTERNS):
        issues.append(_make_issue(path, "SUSPICIOUS_PLACEHOLDER", "Looks like autogenerated placeholder data", 0.1))
    if re.search(r"(.)\1{5,}", value.replace(" ", ""), re.I):
        issues.append(_make_issue(path, "REPEATED_CHARACTER_GARBAGE", "Contains repeated-character garbage", 0.1))
    if len(value) > 8 and not re.search(r"[a-z0-9]", value, re.I):
        issues.append(_make_issue(path, "NON_SEMANTIC_STRING", "String contains no semantic content", 0.1))


def _inspect_object(value: Any, path: str, issues: list) -> None:
    if isinstance(value, list):
        for i, item in enumerate(value):
            _inspect_object(item, f"{path}[{i}]", issues)
        return
    if not isinstance(value, dict):
        if isinstance(value, str):
            _inspect_string(path, value, issues)
        return
    for key, nested in value.items():
        _inspect_object(nested, f"{path}.{key}" if path else key, issues)


def _inspect_resources(
    input_data: dict,
    resource_manager: "ResourceManager",
    issues: list,
) -> None:
    _inspect_resource_fields(input_data, "", resource_manager, issues)
    carrier_accounts = input_data.get("carrier_accounts")
    if isinstance(carrier_accounts, list):
        for i, account in enumerate(carrier_accounts):
            result = resource_manager.validate_carrier_account(account)
            if not result["valid"]:
                issues.append(_make_issue(
                    f"carrier_accounts[{i}]",
                    "UNKNOWN_CARRIER_ACCOUNT",
                    f"Unknown carrier account: {account}",
                    0.0,
                    result["suggestions"],
                ))


def _inspect_resource_fields(
    value: Any,
    path: str,
    resource_manager: "ResourceManager",
    issues: list,
) -> None:
    if isinstance(value, list):
        for i, item in enumerate(value):
            _inspect_resource_fields(item, f"{path}[{i}]", resource_manager, issues)
        return
    if not isinstance(value, dict):
        return

    country = value.get("country")
    if country:
        result = resource_manager.validate_country(country)
        if not result["valid"]:
            key = f"{path}.country" if path else "country"
            issues.append(_make_issue(key, "UNKNOWN_COUNTRY", f"Unknown country: {country}", 0.0, result["suggestions"]))

        # Check state independently — even when country is invalid (mirrors JS behavior)
        state = value.get("state")
        if state:
            result = resource_manager.validate_state(country, state)
            if not result["valid"]:
                key = f"{path}.state" if path else "state"
                issues.append(_make_issue(key, "UNKNOWN_STATE", f"Unknown state/province for {country}: {state}", 0.0, result["suggestions"]))

    if payment_method := value.get("payment_method"):
        result = resource_manager.validate_payment_method(payment_method)
        if not result["valid"]:
            key = f"{path}.payment_method" if path else "payment_method"
            issues.append(_make_issue(key, "UNKNOWN_PAYMENT_METHOD", f"Unknown payment method: {payment_method}", 0.0, result["suggestions"]))

    if predefined_package := value.get("predefined_package"):
        result = resource_manager.validate_package_type(predefined_package)
        if not result["valid"]:
            key = f"{path}.predefined_package" if path else "predefined_package"
            issues.append(_make_issue(key, "UNKNOWN_PACKAGE_TYPE", f"Unknown package type: {predefined_package}", 0.0, result["suggestions"]))

    if carrier := value.get("carrier"):
        result = resource_manager.validate_carrier(carrier)
        if not result["valid"]:
            key = f"{path}.carrier" if path else "carrier"
            issues.append(_make_issue(key, "UNKNOWN_CARRIER", f"Unsupported carrier: {carrier}", 0.0, result["suggestions"]))
        elif service := value.get("service"):
            result = resource_manager.validate_service(carrier, service)
            if not result["valid"]:
                key = f"{path}.service" if path else "service"
                msg = (result["issues"][0].get("message") if result["issues"] else None) or "Unsupported carrier/service combination"
                issues.append(_make_issue(key, "UNSUPPORTED_SERVICE_FOR_CARRIER", msg, 0.0, result["suggestions"]))

    for key, nested in value.items():
        _inspect_resource_fields(nested, f"{path}.{key}" if path else key, resource_manager, issues)


def validate_anti_hallucination(
    input_data: dict,
    *,
    tool_name: str | None = None,
    resource_manager: "ResourceManager | None" = None,
) -> dict[str, Any]:
    issues: list[dict] = []
    _inspect_object(input_data, "", issues)
    validation_exempt = {"validate_carrier", "validate_service"}
    if resource_manager and tool_name not in validation_exempt:
        _inspect_resources(input_data, resource_manager, issues)

    confidence = min((issue.get("confidence", 0.2) for issue in issues), default=1.0)
    return {
        "valid": len(issues) == 0,
        "confidence": confidence,
        "issues": issues,
        "suggestions": [s for issue in issues for s in (issue.get("suggestions") or [])],
    }


def assert_not_hallucinated(
    input_data: dict,
    *,
    tool_name: str | None = None,
    resource_manager: "ResourceManager | None" = None,
) -> None:
    result = validate_anti_hallucination(input_data, tool_name=tool_name, resource_manager=resource_manager)
    if not result["valid"]:
        raise AntiHallucinationError(
            "Input appears unsupported, ambiguous, or AI-generated. Provide exact values from verified resources.",
            details=result,
        )
